---
title: hygienic darkroom retreat
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  recovery-of-the-lost-self:
    title: Recovery of the Lost Self
    output: true
  uploads:
    title: Uploads
    output: true
description: profound rest for the self-healing psyche
baseurl: ''
url: http://darkroomretreat.com
markdown: kramdown
plugins:
- jekyll-feed
include:
- _pages
